server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: products-service
  datasource:
    url: jdbc:h2:file:~/products;AUTO_SERVER=true
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

axon:
  eventhandling:
    processors:
      products-group:
        mode: subscribing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

