server:
  port: 8380
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: payments-service
  datasource:
    url: jdbc:h2:file:~/payments;AUTO_SERVER=true
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


